spring.application.name=Server
server.port=8686

spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_hHW0b7X6g5IKXsKVaeY
spring.datasource.url=jdbc:mysql://avnadmin:AVNS_hHW0b7X6g5IKXsKVaeY@mgbooking-votannamquoc-130504.j.aivencloud.com:22125/defaultdb?ssl-mode=REQUIRED
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database=mysql
spring.jpa.show-sql=true
